/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors for Boodesk React
        'brand-red': '#B70404',
        'brand-green': '#2E8B57',
        'brand-gray': '#333333',
        'brand-light-gray': '#E5E7EB',
        'brand-blue': '#1E40AF',
        'brand-yellow': '#F59E0B',
        'brand-purple': '#7C3AED',
        'brand-orange': '#EA580C',
        'brand-cyan': '#0891B2',
        'brand-pink': '#DB2777',
        'brand-indigo': '#4F46E5',
        'brand-emerald': '#059669',
        'brand-rose': '#E11D48',
        'brand-violet': '#7C3AED',
        'brand-slate': '#475569',
        'brand-zinc': '#52525B',
        'brand-neutral': '#525252',
        'brand-stone': '#78716C',
        'brand-lime': '#65A30D',
        'brand-teal': '#0D9488',
        'brand-sky': '#0284C7',
        'brand-blue-light': '#3B82F6',
        'brand-blue-dark': '#1E3A8A',
        'brand-green-light': '#10B981',
        'brand-green-dark': '#065F46',
        'brand-red-light': '#EF4444',
        'brand-red-dark': '#991B1B',
        'brand-yellow-light': '#F59E0B',
        'brand-yellow-dark': '#92400E',
        'brand-purple-light': '#A855F7',
        'brand-purple-dark': '#581C87',
        'brand-orange-light': '#F97316',
        'brand-orange-dark': '#9A3412',
        'brand-cyan-light': '#06B6D4',
        'brand-cyan-dark': '#0E7490',
        'brand-pink-light': '#EC4899',
        'brand-pink-dark': '#BE185D',
        'brand-indigo-light': '#6366F1',
        'brand-indigo-dark': '#3730A3',
        'brand-emerald-light': '#10B981',
        'brand-emerald-dark': '#047857',
        'brand-rose-light': '#F43F5E',
        'brand-rose-dark': '#BE123C',
        'brand-violet-light': '#8B5CF6',
        'brand-violet-dark': '#5B21B6',
        'brand-slate-light': '#64748B',
        'brand-slate-dark': '#334155',
        'brand-zinc-light': '#71717A',
        'brand-zinc-dark': '#3F3F46',
        'brand-neutral-light': '#737373',
        'brand-neutral-dark': '#404040',
        'brand-stone-light': '#A8A29E',
        'brand-stone-dark': '#57534E',
        'brand-lime-light': '#84CC16',
        'brand-lime-dark': '#4D7C0F',
        'brand-teal-light': '#14B8A6',
        'brand-teal-dark': '#0F766E',
        'brand-sky-light': '#0EA5E9',
        'brand-sky-dark': '#0369A1',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'bounce-in': 'bounceIn 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

