# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app2a.py'],
    pathex=[],
    binaries=[],
    datas=[
    ('16 colors.png', '.'),
    ('256 colors.png', '.'),
    ('3d bar chart.png', '.'),
    ('3d chart.png', '.'),
    ('3d graph.png', '.'),
    ('About.png', '.'),
    ('Add folder.png', '.'),
    ('Add.png', '.'),
    ('Angle.png', '.'),
    ('Apply.png', '.'),
    ('Arc.png', '.'),
    ('Arrow.png', '.'),
    ('Attach.png', '.'),
    ('Back.png', '.'),
    ('Bitmap editor.png', '.'),
    ('Brightness.png', '.'),
    ('Brush.png', '.'),
    ('Camera.png', '.'),
    ('Cancel.png', '.'),
    ('Chart xy.png', '.'),
    ('Check boxes.png', '.'),
    ('Circle.png', '.'),
    ('Clear.png', '.'),
    ('Clipboard.png', '.'),
    ('Close file.png', '.'),
    ('Close folder.png', '.'),
    ('Close.png', '.'),
    ('CMYK.png', '.'),
    ('Coffe.png', '.'),
    ('Coffee.png', '.'),
    ('Color balance.png', '.'),
    ('Color filter.png', '.'),
    ('Color layers.png', '.'),
    ('Color palette.png', '.'),
    ('Color profile.png', '.'),
    ('Color test.png', '.'),
    ('Color.png', '.'),
    ('Comment.png', '.'),
    ('Contrast.png', '.'),
    ('Copy.png', '.'),
    ('Create.png', '.'),
    ('Critical details.png', '.'),
    ('Curve points.png', '.'),
    ('Curve.png', '.'),
    ('Cut.png', '.'),
    ('Danger.png', '.'),
    ('Decrease time.png', '.'),
    ('Delete frame.png', '.'),
    ('Delete frames.png', '.'),
    ('Delete.png', '.'),
    ('Designer.png', '.'),
    ('Diagram.png', '.'),
    ('Down.png', '.'),
    ('Download image.png', '.'),
    ('Download.png', '.'),
    ('Dropper.png', '.'),
    ('E-mail.png', '.'),
    ('Edit page.png', '.'),
    ('Edit text.png', '.'),
    ('Edit.png', '.'),
    ('Ellipse.png', '.'),
    ('Equipment.png', '.'),
    ('Erase.png', '.'),
    ('Eraser.png', '.'),
    ('Error.png', '.'),
    ('Exit.png', '.'),
    ('Export.png', '.'),
    ('Favourites.png', '.'),
    ('Feather.png', '.'),
    ('File exetension.png', '.'),
    ('Fill.png', '.'),
    ('Find.png', '.'),
    ('Fine brush.png', '.'),
    ('Flip horizontally.png', '.'),
    ('Flip vertically.png', '.'),
    ('Flip.png', '.'),
    ('Flow block.png', '.'),
    ('Flower.png', '.'),
    ('Folder.png', '.'),
    ('Form.png', '.'),
    ('Forward.png', '.'),
    ('Frames.png', '.'),
    ('Funnel.png', '.'),
    ('Go down.png', '.'),
    ('Go up.png', '.'),
    ('Gpadient.png', '.'),
    ('Graphic designer.png', '.'),
    ('Graphic file.png', '.'),
    ('Graphic tools.png', '.'),
    ('Grid.png', '.'),
    ('Help book.png', '.'),
    ('Help.png', '.'),
    ('Hexagon.png', '.'),
    ('Hide.png', '.'),
    ('Hint.png', '.'),
    ('Hints.png', '.'),
    ('Home.png', '.'),
    ('Homepage.png', '.'),
    ('HSL.png', '.'),
    ('HSV.png', '.'),
    ('Ico.png', '.'),
    ('Icon wizard.png', '.'),
    ('Import.png', '.'),
    ('Increase time.png', '.'),
    ('Index.png', '.'),
    ('Info.png', '.'),
    ('Key.png', '.'),
    ('Knife.png', '.'),
    ('LAB color model.png', '.'),
    ('Layers.png', '.'),
    ('Left-right.png', '.'),
    ('Left.png', '.'),
    ('Line.png', '.'),
    ('List.png', '.'),
    ('Lock color.png', '.'),
    ('Lock transparency.png', '.'),
    ('Lock.png', '.'),
    ('LOGO.png', '.'),
    ('Magic hat.png', '.'),
    ('Measure.png', '.'),
    ('Microsoft flag.png', '.'),
    ('Monitor.png', '.'),
    ('Monitors.png', '.'),
    ('Mouse pointer.png', '.'),
    ('Mouse.png', '.'),
    ('Move.png', '.'),
    ('Movie.png', '.'),
    ('New clip art.png', '.'),
    ('New file.png', '.'),
    ('New frame.png', '.'),
    ('New frame1.png', '.'),
    ('New image.png', '.'),
    ('New imagelist.png', '.'),
    ('New video.png', '.'),
    ('No.png', '.'),
    ('Objects.png', '.'),
    ('Ok.png', '.'),
    ('Open colors.png', '.'),
    ('Open file.png', '.'),
    ('Open v2.png', '.'),
    ('Open.png', '.'),
    ('Paint over pixels.png', '.'),
    ('Painter.png', '.'),
    ('Pantone.png', '.'),
    ('Paste.png', '.'),
    ('Pen.png', '.'),
    ('Pencil.png', '.'),
    ('Pick color.png', '.'),
    ('Picture.png', '.'),
    ('Pie chart.png', '.'),
    ('Pin.png', '.'),
    ('Pinion.png', '.'),
    ('Pixel editor.png', '.'),
    ('Pixels.png', '.'),
    ('Play.png', '.'),
    ('Preview.png', '.'),
    ('Print.png', '.'),
    ('Problem.png', '.'),
    ('Properties.png', '.'),
    ('Red book.png', '.'),
    ('Red eye removing.png', '.'),
    ('Redo.png', '.'),
    ('Refresh.png', '.'),
    ('Registration.png', '.'),
    ('Registry.png', '.'),
    ('Rename.png', '.'),
    ('Replace pixels.png', '.'),
    ('Resize image.png', '.'),
    ('Restangle.png', '.'),
    ('Revert.png', '.'),
    ('RGB.png', '.'),
    ('Right.png', '.'),
    ('Rotate CCW.png', '.'),
    ('Rotate CW.png', '.'),
    ('Rotate left.png', '.'),
    ('Rotate right.png', '.'),
    ('Rotation.png', '.'),
    ('Rounded rectangle.png', '.'),
    ('Save as.png', '.'),
    ('Save color.png', '.'),
    ('Save data.png', '.'),
    ('Save image.png', '.'),
    ('Save picture.png', '.'),
    ('Save.png', '.'),
    ('Scan film.png', '.'),
    ('Scan image.png', '.'),
    ('Scanner.png', '.'),
    ('Scenario.png', '.'),
    ('Script.png', '.'),
    ('Search computer.png', '.'),
    ('Search folder.png', '.'),
    ('Search online.png', '.'),
    ('Search text.png', '.'),
    ('Search.png', '.'),
    ('Select gpadient.png', '.'),
    ('Selection.png', '.'),
    ('Settings.png', '.'),
    ('Sharpness.png', '.'),
    ('Show.png', '.'),
    ('Sizes.png', '.'),
    ('Smooth line.png', '.'),
    ('Smooth.png', '.'),
    ('Spell checking.png', '.'),
    ('Spiral.png', '.'),
    ('Spray.png', '.'),
    ('Square.png', '.'),
    ('Stop playing.png', '.'),
    ('Stop.png', '.'),
    ('Synchronize.png', '.'),
    ('Tag.png', '.'),
    ('Target.png', '.'),
    ('Target1.png', '.'),
    ('Test line.png', '.'),
    ('Text color.png', '.'),
    ('Text replace.png', '.'),
    ('Text tool.png', '.'),
    ('Time.png', '.'),
    ('Tip of the day.png', '.'),
    ('To do list.png', '.'),
    ('Tools.png', '.'),
    ('Touch.png', '.'),
    ('Transparency.png', '.'),
    ('Transparent background.png', '.'),
    ('Transparent color.png', '.'),
    ('Triangle.png', '.'),
    ('True color.png', '.'),
    ('Undo.png', '.'),
    ('Units.png', '.'),
    ('Unlock.png', '.'),
    ('Up-down.png', '.'),
    ('Up.png', '.'),
    ('Upload image.png', '.'),
    ('Wait.png', '.'),
    ('Warning.png', '.'),
    ('Web designer.png', '.'),
    ('Webcam.png', '.'),
    ('Wide brush.png', '.'),
    ('Wizard.png', '.'),
    ('Work area.png', '.'),
    ('Writing pencil.png', '.'),
    ('Wrong.png', '.'),
    ('Yes.png', '.'),
    ('YUV color space.png', '.'),
    ('Zoom auto.png', '.'),
    ('Zoom in.png', '.'),
    ('Zoom out.png', '.'),
    ('Zoom.png', '.'),
    ('pomodoro_motivational_messages.json', '.'),
    ('pomodoro_settings.json', '.'),
    ('pomodoro_subjects.xlsx', '.'),
    ('pomodoro_tasks.xlsx', '.'),
    ('life_goals.xlsx', '.'),
    ('trello_data.json', '.'),
    ('trello_members.xlsx', '.'),
    ('trello_subjects.xlsx', '.'),
    ('users.xlsx', '.'),
    ('study_log.xlsx', '.')
],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app2a',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
